receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
        - https://localhost:7258
        cors_allowed_headers:
        - "*"

processors:
  batch:
  # queued_retry:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:
    #loglevel: debug

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  file:
    path: /etc/output/logs.json

  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    instrumentation_key: 5880bf03-438b-4c3c-aefc-586f83e73e32
    maxbatchsize: 100
    maxbatchinterval: 10s

  elastic:
    apm_server_url: test

  otlp/elastic:
    endpoint: test
    headers:
      Authorization: "Bearer 12345"

  # elasticsearch:
  #   endpoints: [https://otel-logs-elasticsearch.es.westeurope.azure.elastic-cloud.com:9243]
  #   cloudid: otel-logs-elasticsearch:d2VzdGV1cm9wZS5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo5MjQzJDIyNzBkOTJkYWRiOTQxNTdhNjliYmE5MmZjNGQ5MmMxJGNhMDFiYTI1ZWZkODQ2YzlhMDg3NzFkMzlhMmUyODQx

  # awscloudwatchlogs:
  #   log_group_name: "otel-research-testing-logs"
  #   log_stream_name: "otel-research-testing-logs-stream"
  #   region: "eu-north-1"
  #   endpoint: "logs.eu-north-1.amazonaws.com"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]
